env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi: off
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/sort-type-union-intersection-members": error
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: comma
        requireLast: false
      overrides:
        interface:
          multiline:
            delimiter: semi
            requireLast: true
